namespace GnomeShellRpc.GiStubGen
{
	/**
	 * Walk an installed typelib via GIRepository and emit Vala stubs.
	 *
	 * {@link Application} is the CLI only; this class owns generation.
	 * Each {@link GI.InfoType} is handled by its own emit method.
	 *
	 * == Example ==
	 *
	 * {{{
	 * GI.Repository.get_default().require("GiRpcSmoke", "1.0", 0);
	 * var gen = new Generator() { deny = deny };
	 * gen.emit("GiRpcSmoke", "GiRpcSmoke_generated.vala");
	 * }}}
	 */
	public class Generator : GLib.Object
	{
		/** Denylisted symbols skipped on emit; {@code Type.method} or bare name. */
		public string[] deny = {};

		/** When set, write a gap summary markdown file after emit. */
		public string missing_out_path = "";

		private const string RUNTIME = "GnomeShellRpc.GiStub.Runtime";

		private struct Gap {
			public string symbol;
			public string reason;
			public string detail;
		}

		private Gap[] gaps = {};
		private int wired_callables = 0;

		/**
		 * Write Vala stubs for {@code ns}, skipping {@link deny} symbols.
		 *
		 * @param ns GI namespace
		 * @param out_path path for the generated {@code .vala} file
		 * @throws GLib.Error if nothing was emitted or the file cannot be written
		 */
		public void emit(string ns, string out_path) throws GLib.Error
		{
			this.gaps = {};
			this.wired_callables = 0;

			var stream = GLib.FileStream.open(out_path, "w");
			if (stream == null) {
				throw new GLib.IOError.FAILED("cannot write " + out_path);
			}
			stream.puts(@"
/* Generated by gi-stub-gen — do not edit */
namespace $(ns)
{
");

			var emitted = 0;
			var n_infos = GI.Repository.get_default().get_n_infos(ns);
			for (var i = 0; i < n_infos; i++) {
				var info = GI.Repository.get_default().get_info(ns, i);
				switch (info.get_type()) {
					case GI.InfoType.FUNCTION:
						emitted += this.emit_function(stream, ns, (GI.FunctionInfo)info);
						continue;
					case GI.InfoType.OBJECT:
						emitted += this.emit_object(stream, ns, (GI.ObjectInfo)info);
						continue;
					case GI.InfoType.ENUM:
						emitted += this.emit_enum(stream, (GI.EnumInfo)info);
						continue;
					case GI.InfoType.FLAGS:
						emitted += this.emit_flags(stream, (GI.EnumInfo)info);
						continue;
					case GI.InfoType.CONSTANT:
						emitted += this.emit_constant(stream, (GI.ConstantInfo)info);
						continue;
					case GI.InfoType.STRUCT:
						emitted += this.emit_struct(stream, ns, (GI.StructInfo)info);
						continue;
					case GI.InfoType.INTERFACE:
						emitted += this.emit_interface(stream, ns, (GI.InterfaceInfo)info);
						continue;
					case GI.InfoType.CALLBACK:
						emitted += this.emit_callback(stream, ns, (GI.CallbackInfo)info);
						continue;
					default:
						this.gap(
							info.get_name(),
							"unhandled_info",
							info.get_type().to_string()
						);
						continue;
				}
			}
			stream.puts("}\n");
			stream = null;

			if (emitted == 0) {
				GLib.FileUtils.unlink(out_path);
				throw new GLib.IOError.FAILED("emit: no matching stubs");
			}
			this.write_missing_summary(ns);
			GLib.print("emitted %d stub(s) → %s\n", emitted, out_path);
		}

		/**
		 * Emit a namespace function.
		 *
		 * @param stream output Vala file
		 * @param ns GI namespace
		 * @param fi function info
		 * @return number of stubs written (0 or 1)
		 */
		private int emit_function(GLib.FileStream stream, string ns, GI.FunctionInfo fi)
		{
			var name = fi.get_name();
			if (name in this.deny) {
				this.gap(this.wire_symbol(ns, "", name), "denied");
				return 0;
			}
			return this.emit_callable(stream, ns, "", fi, "ns");
		}

		/**
		 * Emit an object type and recurse into its methods.
		 *
		 * @param stream output Vala file
		 * @param ns GI namespace
		 * @param oi object info
		 * @return number of stubs written (class counts as 1 when emitted)
		 */
		private int emit_object(GLib.FileStream stream, string ns, GI.ObjectInfo oi)
		{
			var class_name = oi.get_name();
			if (class_name in this.deny) {
				this.gap(this.wire_symbol(ns, class_name, ""), "denied", "class");
				return 0;
			}

			var parent = "GLib.Object";
			if (oi.get_parent() != null) {
				parent = this.info_name(ns, oi.get_parent());
			}

			stream.puts(@"
	public class $(class_name) : $(parent)
	{
");
			var methods = 0;
			for (var m = 0; m < oi.get_n_methods(); m++) {
				methods += this.emit_callable(stream, ns, class_name, oi.get_method(m), "class");
			}
			stream.puts("	}\n");
			return 1 + methods;
		}

		/**
		 * Emit an enum type.
		 *
		 * @param stream output Vala file
		 * @param ei enum info
		 * @return 1 if written
		 */
		private int emit_enum(GLib.FileStream stream, GI.EnumInfo ei)
		{
			return this.emit_enum_values(stream, ei, false);
		}

		/**
		 * Emit a flags type.
		 *
		 * @param stream output Vala file
		 * @param ei flags info (same GI shape as enum)
		 * @return 1 if written
		 */
		private int emit_flags(GLib.FileStream stream, GI.EnumInfo ei)
		{
			return this.emit_enum_values(stream, ei, true);
		}

		private int emit_enum_values(GLib.FileStream stream, GI.EnumInfo ei, bool is_flags)
		{
			if (ei.get_name() in this.deny) {
				this.gap(ei.get_name(), "denied", "enum");
				return 0;
			}
			if (is_flags) {
				stream.puts("\n	[Flags]\n");
			} else {
				stream.puts("\n");
			}
			stream.puts(@"	public enum $(ei.get_name())
	{
");
			for (var i = 0; i < ei.get_n_values(); i++) {
				var vi = ei.get_value(i);
				stream.puts(@"		$(vi.get_name()) = $(vi.get_value()),
");
			}
			stream.puts("	}\n");
			return 1;
		}

		/**
		 * Emit a namespace constant.
		 *
		 * @param stream output Vala file
		 * @param ci constant info
		 * @return 1 if written
		 */
		private int emit_constant(GLib.FileStream stream, GI.ConstantInfo ci)
		{
			if (ci.get_name() in this.deny) {
				this.gap(ci.get_name(), "denied", "constant");
				return 0;
			}
			GI.Argument value;
			ci.get_value(out value);
			switch (ci.get_type().get_tag()) {
				case GI.TypeTag.BOOLEAN:
					stream.puts(@"
	public const bool $(ci.get_name()) = $(value.v_boolean);
");
					return 1;
				case GI.TypeTag.INT8:
					stream.puts(@"
	public const int8 $(ci.get_name()) = $(value.v_int8);
");
					return 1;
				case GI.TypeTag.UINT8:
					stream.puts(@"
	public const uint8 $(ci.get_name()) = $(value.v_uint8);
");
					return 1;
				case GI.TypeTag.INT16:
					stream.puts(@"
	public const int16 $(ci.get_name()) = $(value.v_int16);
");
					return 1;
				case GI.TypeTag.UINT16:
					stream.puts(@"
	public const uint16 $(ci.get_name()) = $(value.v_uint16);
");
					return 1;
				case GI.TypeTag.INT32:
					stream.puts(@"
	public const int32 $(ci.get_name()) = $(value.v_int32);
");
					return 1;
				case GI.TypeTag.UINT32:
					stream.puts(@"
	public const uint32 $(ci.get_name()) = $(value.v_uint32);
");
					return 1;
				case GI.TypeTag.INT64:
					stream.puts(@"
	public const int64 $(ci.get_name()) = $(value.v_int64);
");
					return 1;
				case GI.TypeTag.UINT64:
					stream.puts(@"
	public const uint64 $(ci.get_name()) = $(value.v_uint64);
");
					return 1;
				case GI.TypeTag.FLOAT:
					stream.puts(@"
	public const float $(ci.get_name()) = $(value.v_float);
");
					return 1;
				case GI.TypeTag.DOUBLE:
					stream.puts(@"
	public const double $(ci.get_name()) = $(value.v_double);
");
					return 1;
				case GI.TypeTag.UTF8:
				case GI.TypeTag.FILENAME:
					stream.puts(@"
	public const string $(ci.get_name()) = \"$(value.v_string)\";
");
					return 1;
				default:
					this.gap(
						ci.get_name(),
						"unhandled_constant",
						ci.get_type().get_tag().to_string()
					);
					return 0;
			}
		}

		/**
		 * Emit a struct (skips GType class structs).
		 *
		 * @param stream output Vala file
		 * @param ns GI namespace
		 * @param si struct info
		 * @return 1 if written
		 */
		private int emit_struct(GLib.FileStream stream, string ns, GI.StructInfo si)
		{
			if (si.is_gtype_struct()) {
				return 0;
			}
			if (si.get_name() in this.deny) {
				this.gap(si.get_name(), "denied", "struct");
				return 0;
			}
			stream.puts(@"
	public struct $(si.get_name())
	{
");
			for (var f = 0; f < si.get_n_fields(); f++) {
				var field = si.get_field(f);
				var ft = this.type_vala(ns, field.get_type());
				if (ft == "") {
					this.gap(
						@"$(si.get_name()).$(field.get_name())",
						"unmapped_field",
						field.get_type().get_tag().to_string()
					);
					continue;
				}
				stream.puts(@"		public $(ft) $(field.get_name());
");
			}
			stream.puts("	}\n");
			return 1;
		}

		/**
		 * Emit an interface and its methods.
		 *
		 * @param stream output Vala file
		 * @param ns GI namespace
		 * @param ii interface info
		 * @return number of stubs written
		 */
		private int emit_interface(GLib.FileStream stream, string ns, GI.InterfaceInfo ii)
		{
			var iface_name = ii.get_name();
			if (iface_name in this.deny) {
				this.gap(iface_name, "denied", "interface");
				return 0;
			}

			stream.puts(@"
	public interface $(iface_name) : GLib.Object
	{
");
			var methods = 0;
			for (var m = 0; m < ii.get_n_methods(); m++) {
				methods += this.emit_callable(stream, ns, iface_name, ii.get_method(m), "iface");
			}
			stream.puts("	}\n");
			return 1 + methods;
		}

		/**
		 * Emit a callback as a Vala delegate.
		 *
		 * @param stream output Vala file
		 * @param ns GI namespace
		 * @param ci callback info
		 * @return 1 if written
		 */
		private int emit_callback(GLib.FileStream stream, string ns, GI.CallbackInfo ci)
		{
			if (ci.get_name() in this.deny) {
				this.gap(ci.get_name(), "denied", "callback");
				return 0;
			}
			var ret = this.type_vala(ns, ci.get_return_type());
			if (ret == "") {
				this.gap(
					ci.get_name(),
					"unhandled_callback",
					"return " + ci.get_return_type().get_tag().to_string()
				);
				return 0;
			}
			string[] args = {};
			for (var a = 0; a < ci.get_n_args(); a++) {
				var arg = ci.get_arg(a);
				var at = this.type_vala(ns, arg.get_type());
				if (at == "") {
					this.gap(
						ci.get_name(),
						"unhandled_callback",
						@"arg $(arg.get_name()) $(arg.get_type().get_tag().to_string())"
					);
					return 0;
				}
				args += this.arg_decl(arg, at);
			}
			stream.puts(@"
	public delegate $(ret) $(ci.get_name())($(string.joinv(", ", args)));
");
			return 1;
		}

		/**
		 * Emit one callable (namespace function or method) with a stub or utf8 RPC body.
		 *
		 * @param stream output Vala file
		 * @param ns GI namespace
		 * @param type_name owning type name, or empty for namespace functions
		 * @param fi function info
		 * @param kind {@code ns}, {@code class}, or {@code iface}
		 * @return 1 if written
		 */
		private int emit_callable(
			GLib.FileStream stream,
			string ns,
			string type_name,
			GI.FunctionInfo fi,
			string kind
		)
		{
			var name = fi.get_name();
			var symbol = this.wire_symbol(ns, type_name, name);
			if (name in this.deny) {
				this.gap(symbol, "denied");
				return 0;
			}
			if (type_name != ""
				&& ((type_name + "." + name) in this.deny || type_name in this.deny)) {
				this.gap(symbol, "denied");
				return 0;
			}

			var flags = fi.get_flags();
			var is_constructor = (flags & GI.FunctionInfoFlags.IS_CONSTRUCTOR) != 0;
			if (is_constructor && kind != "class") {
				this.gap(symbol, "constructor", "not on class");
				return 0;
			}

			var ret = is_constructor
				? type_name
				: this.type_vala(ns, fi.get_return_type());
			if (ret == "") {
				this.gap(
					symbol,
					"unmapped_return",
					fi.get_return_type().get_tag().to_string()
				);
				return 0;
			}

			string[] args = {};
			for (var a = 0; a < fi.get_n_args(); a++) {
				var arg = fi.get_arg(a);
				var at = this.type_vala(ns, arg.get_type());
				if (at == "") {
					this.gap(
						symbol,
						"unmapped_arg",
						@"$(arg.get_name()) $(arg.get_type().get_tag().to_string())"
					);
					return 0;
				}
				args += this.arg_decl(arg, at);
			}

			var tab = kind == "ns" ? "	" : "		";
			var arglist = string.joinv(", ", args);
			/*
			 * Domain wire names: no RPC- prefix (Daemon / Live-* only).
			 * Nested type → hyphen object prefix (Meta-Window.minimize),
			 * same idea as RPC-Live-Remote.ref.
			 */
			string rpc;
			if (type_name == "") {
				rpc = @"$(ns).$(name)";
			} else {
				rpc = @"$(ns)-$(type_name).$(name)";
			}

			if (kind == "iface") {
				if (ret == "void") {
					stream.puts(@"
$(tab)public abstract void $(name)($(arglist));
");
				} else {
					stream.puts(@"
$(tab)public abstract $(ret) $(name)($(arglist));
");
				}
				return 1;
			}

			var instance = "null";
			if (!is_constructor && kind == "class") {
				instance = "this";
			}
			var indent = tab + "\t";
			if (this.callable_wireable(fi, ns)) {
				if (is_constructor) {
					stream.puts(
						tab + @"public $(type_name)($(arglist)) {
"
					);
				} else {
					stream.puts(tab + @"public $(ret) $(name)($(arglist)) {
");
				}
				this.emit_call_values_body(
					stream, ns, indent, rpc, instance, fi, ret, is_constructor
				);
				stream.puts(tab + "}\n");
				this.wired_callables++;
				return 1;
			}

			this.gap(symbol, "not_wired");

			if (is_constructor) {
				stream.puts(
					tab + @"public $(type_name)($(arglist)) {
$(indent)GLib.error(\"gi-stub: $(rpc) not wired\");
$(tab)}
"
				);
			} else if (ret == "void") {
				stream.puts(tab + @"public void $(name)($(arglist)) {
$(indent)GLib.error(\"gi-stub: $(rpc) not wired\");
$(tab)}
");
			} else {
				stream.puts(tab + @"public $(ret) $(name)($(arglist)) {
$(indent)GLib.error(\"gi-stub: $(rpc) not wired\");
$(tab)}
");
			}
			return 1;
		}

		private void emit_call_values_body(
			GLib.FileStream stream,
			string ns,
			string indent,
			string rpc,
			string instance,
			GI.FunctionInfo fi,
			string ret_vala,
			bool is_constructor = false
		)
		{
			if (is_constructor) {
				stream.puts(indent + "Object();\n");
			}
			string[] value_names = {};
			for (var a = 0; a < fi.get_n_args(); a++) {
				var arg = fi.get_arg(a);
				var dir = arg.get_direction();
				if (dir != GI.Direction.IN && dir != GI.Direction.INOUT) {
					continue;
				}
				var arg_name = arg.get_name();
				var at = this.type_vala(ns, arg.get_type());
				var suffix = this.value_suffix(ns, arg.get_type());
				var val_name = this.emit_value_set(
					stream, indent, arg_name, at, suffix
				);
				value_names += val_name;
			}

			var values_arg = "";
			if (value_names.length > 0) {
				values_arg = ", { " + string.joinv(", ", value_names) + " }";
			}
			var call = @"$(RUNTIME).call_values(\"$(rpc)\", $(instance)$(values_arg))";

			var need_response = ret_vala != "void"
				|| this.has_out_values(fi);
			if (!need_response) {
				stream.puts(indent + call + ";\n");
				return;
			}

			stream.puts(indent + "var response = " + call + ";\n");

			var value_idx = 0;
			var has_return = ret_vala != "void";
			var has_outs = this.has_out_values(fi);
			if (has_return) {
				if (this.return_is_object_list(ns, fi.get_return_type())) {
					this.emit_list_return(
						stream, indent, ns, fi.get_return_type()
					);
					return;
				}
				if (this.type_is_gobject(fi.get_return_type())) {
					if (is_constructor) {
						stream.puts(indent + @"var _stub = ($(ret_vala)) response.result.get(0);
");
						stream.puts(
							indent + @"this.set_data(\"gsr-lease-id\", _stub.get_data<string>(\"gsr-lease-id\"));
"
						);
						return;
					}
					if (!has_outs) {
						stream.puts(indent + @"return ($(ret_vala)) response.result.get(0);
");
						return;
					}
					stream.puts(indent + @"var __ret = ($(ret_vala)) response.result.get(0);
");
				} else {
					var ret_suffix = this.value_suffix(ns, fi.get_return_type());
					if (!has_outs) {
						this.emit_value_get(
							stream, indent, ret_vala, ret_suffix, 0, true
						);
						return;
					}
					this.emit_value_get(
						stream, indent, ret_vala, ret_suffix, 0, false
					);
					value_idx = 1;
				}
			}

			for (var a = 0; a < fi.get_n_args(); a++) {
				var arg = fi.get_arg(a);
				var dir = arg.get_direction();
				if (dir != GI.Direction.OUT && dir != GI.Direction.INOUT) {
					continue;
				}
				var arg_name = arg.get_name();
				var at = this.type_vala(ns, arg.get_type());
				var suffix = this.value_suffix(ns, arg.get_type());
				this.emit_value_get(
					stream, indent, at, suffix, value_idx, false, arg_name
				);
				value_idx++;
			}

			if (has_return && has_outs) {
				stream.puts(indent + "return __ret;\n");
			}
		}

		private void emit_value_get(
			GLib.FileStream stream,
			string indent,
			string vala_type,
			string suffix,
			int value_idx,
			bool is_return,
			string assign_name = ""
		)
		{
			if (suffix == "boxed") {
				this.emit_value_get_boxed(
					stream, indent, vala_type, value_idx, is_return, assign_name
				);
				return;
			}

			var idx = value_idx.to_string();
			string expr;
			switch (suffix) {
				case "enum":
					expr = @"($(vala_type)) response.values.get($(idx)).get_enum()";
					break;
				case "flags":
					expr = @"($(vala_type)) response.values.get($(idx)).get_flags()";
					break;
				default:
					expr = @"response.values.get($(idx)).get_$(suffix)()";
					break;
			}

			if (is_return) {
				stream.puts(indent + @"return $(expr);
");
				return;
			}
			if (assign_name != "") {
				stream.puts(indent + @"$(assign_name) = $(expr);
");
				return;
			}
			stream.puts(indent + @"var __ret = $(expr);
");
		}

		private string emit_value_set(
			GLib.FileStream stream,
			string indent,
			string arg_name,
			string vala_type,
			string suffix
		)
		{
			var val_name = arg_name + "_val";
			switch (suffix) {
				case "boxed":
					stream.puts(
						indent + @"var $(val_name) = GLib.Value(typeof(GLib.Bytes));
"
					);
					stream.puts(indent + @"unsafe {
");
					stream.puts(
						indent + @"	uint8[] _$(arg_name)_data = new uint8[sizeof($(vala_type))];
"
					);
					stream.puts(
						indent + @"	*(($(vala_type))*) _$(arg_name)_data = $(arg_name);
"
					);
					stream.puts(
						indent + @"	$(val_name).set_boxed(new GLib.Bytes(_$(arg_name)_data));
"
					);
					stream.puts(indent + @"}
");
					break;
				case "object":
					stream.puts(
						indent + @"var $(val_name) = GLib.Value(typeof($(vala_type)));
"
					);
					stream.puts(
						indent + @"$(val_name).set_object($(arg_name));
"
					);
					break;
				default:
					stream.puts(
						indent + @"var $(val_name) = GLib.Value(typeof($(vala_type)));
"
					);
					switch (suffix) {
						case "enum":
							stream.puts(
								indent + @"$(val_name).set_enum((int) $(arg_name));
"
							);
							break;
						case "flags":
							stream.puts(
								indent + @"$(val_name).set_flags((uint) $(arg_name));
"
							);
							break;
						default:
							stream.puts(
								indent + @"$(val_name).set_$(suffix)($(arg_name));
"
							);
							break;
					}
					break;
			}
			return val_name;
		}

		private void emit_value_get_boxed(
			GLib.FileStream stream,
			string indent,
			string vala_type,
			int value_idx,
			bool is_return,
			string assign_name
		)
		{
			var idx = value_idx.to_string();
			stream.puts(indent + @"unsafe {
");
			stream.puts(
				indent + @"	var _blob = (GLib.Bytes) response.values.get($(idx)).get_boxed();
"
			);
			if (is_return) {
				stream.puts(
					indent + @"	return *(($(vala_type))*) _blob.get_data();
"
				);
				stream.puts(indent + @"}
");
				return;
			}
			if (assign_name != "") {
				stream.puts(
					indent + @"	$(assign_name) = *(($(vala_type))*) _blob.get_data();
"
				);
				stream.puts(indent + @"}
");
				return;
			}
			stream.puts(indent + @"$(vala_type) __ret;
");
			stream.puts(
				indent + @"	__ret = *(($(vala_type))*) _blob.get_data();
"
			);
			stream.puts(indent + @"}
");
		}

		private bool has_out_values(GI.FunctionInfo fi)
		{
			for (var a = 0; a < fi.get_n_args(); a++) {
				var dir = fi.get_arg(a).get_direction();
				if (dir == GI.Direction.OUT || dir == GI.Direction.INOUT) {
					return true;
				}
			}
			return false;
		}

		private bool callable_wireable(GI.FunctionInfo fi, string ns)
		{
			for (var a = 0; a < fi.get_n_args(); a++) {
				var arg = fi.get_arg(a);
				var dir = arg.get_direction();
				if (dir != GI.Direction.IN
					&& dir != GI.Direction.INOUT
					&& dir != GI.Direction.OUT) {
					continue;
				}
				var at = arg.get_type();
				if (dir == GI.Direction.INOUT
					&& (this.type_is_boxed_blob(at)
						|| this.type_is_gobject(at))) {
					return false;
				}
				if (this.type_is_gobject(at)) {
					var info = at.get_interface();
					if (info == null || info.get_namespace() != ns) {
						return false;
					}
					if (dir != GI.Direction.IN) {
						return false;
					}
					continue;
				}
				if (this.value_suffix(ns, at) == "") {
					return false;
				}
			}

			if (fi.get_return_type().get_tag() == GI.TypeTag.VOID) {
				return true;
			}
			if (this.return_is_object_list(ns, fi.get_return_type())) {
				return true;
			}
			if (this.type_is_gobject(fi.get_return_type())) {
				return true;
			}
			return this.value_suffix(ns, fi.get_return_type()) != "";
		}

		private bool return_is_object_list(string ns, GI.TypeInfo ti)
		{
			if (ti.get_tag() != GI.TypeTag.GLIST
				&& ti.get_tag() != GI.TypeTag.GSLIST) {
				return false;
			}
			var elem = ti.get_param_type(0);
			if (!this.type_is_gobject(elem)) {
				return false;
			}
			var info = elem.get_interface();
			return info != null && info.get_namespace() == ns;
		}

		private string list_return_vala(string ns, GI.TypeInfo ti)
		{
			var elem = ti.get_param_type(0);
			var elem_vala = this.type_vala(ns, elem);
			if (elem_vala == "") {
				return "";
			}
			if (ti.get_tag() == GI.TypeTag.GLIST) {
				return @"GLib.List<$(elem_vala)>";
			}
			if (ti.get_tag() == GI.TypeTag.GSLIST) {
				return @"GLib.SList<$(elem_vala)>";
			}
			return "";
		}

		private void emit_list_return(
			GLib.FileStream stream,
			string indent,
			string ns,
			GI.TypeInfo ret_type
		)
		{
			var ret_vala = this.list_return_vala(ns, ret_type);
			var elem_vala = this.type_vala(ns, ret_type.get_param_type(0));
			stream.puts(indent + @"var _list = new $(ret_vala)();
");
			stream.puts(indent + @"for (var _i = 0; _i < response.result.size; _i++) {
");
			stream.puts(
				indent + @"	_list.append(($(elem_vala)) response.result.get(_i));
"
			);
			stream.puts(indent + @"}
");
			stream.puts(indent + @"return _list;
");
		}

		private bool type_is_gobject(GI.TypeInfo ti)
		{
			if (ti.get_tag() != GI.TypeTag.INTERFACE) {
				return false;
			}
			var info = ti.get_interface();
			return info != null && info.get_type() == GI.InfoType.OBJECT;
		}

		/** GI scalar tag → {@code set_*} / {@code get_*} suffix, or {@code ""}. */
		private string value_suffix(string ns, GI.TypeInfo ti)
		{
			switch (ti.get_tag()) {
				case GI.TypeTag.BOOLEAN: return "boolean";
				case GI.TypeTag.INT8:
				case GI.TypeTag.INT16:
				case GI.TypeTag.INT32: return "int";
				case GI.TypeTag.UINT8: return "uchar";
				case GI.TypeTag.UINT16:
				case GI.TypeTag.UINT32:
				case GI.TypeTag.UNICHAR: return "uint";
				case GI.TypeTag.INT64: return "int64";
				case GI.TypeTag.UINT64: return "uint64";
				case GI.TypeTag.FLOAT: return "float";
				case GI.TypeTag.DOUBLE: return "double";
				case GI.TypeTag.UTF8:
				case GI.TypeTag.FILENAME: return "string";
				case GI.TypeTag.INTERFACE:
					var es = this.enum_value_suffix(ti);
					if (es != "") {
						return es;
					}
					if (this.type_is_gobject(ti)) {
						var info = ti.get_interface();
						if (info != null && info.get_namespace() == ns) {
							return "object";
						}
					}
					if (this.type_is_boxed_blob(ti)) {
						return "boxed";
					}
					return "";
				default: return "";
			}
		}

		private bool type_is_boxed_blob(GI.TypeInfo ti)
		{
			if (ti.get_tag() != GI.TypeTag.INTERFACE) {
				return false;
			}
			var info = ti.get_interface();
			if (info == null) {
				return false;
			}
			if (info.get_type() == GI.InfoType.UNION) {
				return true;
			}
			if (info.get_type() != GI.InfoType.STRUCT
				&& info.get_type() != GI.InfoType.BOXED) {
				return false;
			}
			return !((GI.StructInfo) info).is_gtype_struct();
		}

		private string enum_value_suffix(GI.TypeInfo ti)
		{
			if (ti.get_tag() != GI.TypeTag.INTERFACE) {
				return "";
			}
			var info = ti.get_interface();
			if (info == null) {
				return "";
			}
			if (info.get_type() == GI.InfoType.FLAGS) {
				return "flags";
			}
			if (info.get_type() == GI.InfoType.ENUM) {
				return "enum";
			}
			return "";
		}

		private string arg_decl(GI.ArgInfo arg, string type_name)
		{
			switch (arg.get_direction()) {
				case GI.Direction.OUT:
					return "out " + type_name + " " + arg.get_name();
				case GI.Direction.INOUT:
					return "ref " + type_name + " " + arg.get_name();
				default:
					return type_name + " " + arg.get_name();
			}
		}

		private string info_name(string ns, GI.BaseInfo info)
		{
			var info_ns = info.get_namespace();
			if (info_ns == null || info_ns == "") {
				return info.get_name();
			}
			if (info_ns == "GObject" && info.get_name() == "Object") {
				return "GLib.Object";
			}
			if (info_ns == ns) {
				return info.get_name();
			}
			if (info_ns == "GObject") {
				return "GLib." + info.get_name();
			}
			return info_ns + "." + info.get_name();
		}

		private string type_vala(string ns, GI.TypeInfo ti)
		{
			switch (ti.get_tag()) {
				case GI.TypeTag.VOID: return "void";
				case GI.TypeTag.BOOLEAN: return "bool";
				case GI.TypeTag.INT8: return "int8";
				case GI.TypeTag.UINT8: return "uint8";
				case GI.TypeTag.INT16: return "int16";
				case GI.TypeTag.UINT16: return "uint16";
				case GI.TypeTag.INT32: return "int32";
				case GI.TypeTag.UINT32: return "uint32";
				case GI.TypeTag.INT64: return "int64";
				case GI.TypeTag.UINT64: return "uint64";
				case GI.TypeTag.FLOAT: return "float";
				case GI.TypeTag.DOUBLE: return "double";
				case GI.TypeTag.GTYPE: return "GLib.Type";
				case GI.TypeTag.UTF8:
				case GI.TypeTag.FILENAME: return "string";
				case GI.TypeTag.UNICHAR: return "unichar";
				case GI.TypeTag.ERROR: return "GLib.Error";
				case GI.TypeTag.GLIST:
				case GI.TypeTag.GSLIST:
					if (!this.return_is_object_list(ns, ti)) {
						return "";
					}
					return this.list_return_vala(ns, ti);
				case GI.TypeTag.INTERFACE:
					var iface = ti.get_interface();
					if (iface == null) {
						return "";
					}
					return this.info_name(ns, iface);
				default: return "";
			}
		}

		private void gap(string symbol, string reason, string detail = "")
		{
			this.gaps += Gap() {
				symbol = symbol,
				reason = reason,
				detail = detail,
			};
		}

		private string wire_symbol(string ns, string type_name, string name)
		{
			if (type_name == "") {
				return @"$(ns).$(name)";
			}
			if (name == "") {
				return @"$(ns)-$(type_name)";
			}
			return @"$(ns)-$(type_name).$(name)";
		}

		private void write_missing_summary(string ns) throws GLib.Error
		{
			if (this.missing_out_path == "") {
				return;
			}

			var stream = GLib.FileStream.open(this.missing_out_path, "w");
			if (stream == null) {
				throw new GLib.IOError.FAILED(
					"cannot write " + this.missing_out_path
				);
			}

			int denied = 0;
			int not_wired = 0;
			int skipped = 0;
			var reason_counts = new Gee.HashMap<string, int>();
			foreach (var entry in this.gaps) {
				if (entry.reason == "denied") {
					denied++;
					continue;
				}
				if (entry.reason == "not_wired") {
					not_wired++;
				} else {
					skipped++;
				}
				if (!reason_counts.has_key(entry.reason)) {
					reason_counts[entry.reason] = 0;
				}
				reason_counts[entry.reason] = reason_counts[entry.reason] + 1;
			}
			var gap_total = not_wired + skipped;

			stream.puts(@"# $(ns) — gi-stub-gen gaps

Auto-generated. **Goal: zero gaps** (every callable either wires
`call_values` or is intentionally denied).

");
			stream.puts("| | Count |\n");
			stream.puts("|---|---:|\n");
			stream.puts(@"| Wired callables | $(this.wired_callables) |
");
			stream.puts(@"| Not wired (placeholder stub) | $(not_wired) |
");
			stream.puts(@"| Skipped (no stub) | $(skipped) |
");
			stream.puts(@"| Denied | $(denied) |
");
			stream.puts(@"| **Gaps** | **$(gap_total)** |

");

			if (gap_total == 0) {
				stream.puts("No gaps.\n");
				stream = null;
				GLib.print(
					"gaps 0 → %s\n", this.missing_out_path
				);
				return;
			}

			stream.puts("## Gaps by reason\n\n");
			stream.puts("| Reason | Count |\n");
			stream.puts("|---|---:|\n");
			string[] reason_order = {
				"not_wired",
				"unmapped_return",
				"unmapped_arg",
				"constructor",
				"unhandled_callback",
				"unhandled_constant",
				"unhandled_info",
				"unmapped_field",
			};
			string[] reasons = {};
			foreach (var reason in reason_order) {
				if (!reason_counts.has_key(reason)) {
					continue;
				}
				reasons += reason;
				stream.puts(@"| $(reason) | $(reason_counts[reason]) |
");
			}

			stream.puts("\n## Gap list\n\n");
			foreach (var reason in reasons) {
				stream.puts(@"### $(reason)

");
				foreach (var entry in this.gaps) {
					if (entry.reason != reason) {
						continue;
					}
					if (entry.detail != "") {
						stream.puts(
							@"- `$(entry.symbol)` — $(entry.detail)
"
						);
					} else {
						stream.puts(@"- `$(entry.symbol)`
");
					}
				}
				stream.puts("\n");
			}

			if (denied > 0) {
				stream.puts("## Denied\n\n");
				foreach (var entry in this.gaps) {
					if (entry.reason != "denied") {
						continue;
					}
					if (entry.detail != "") {
						stream.puts(
							@"- `$(entry.symbol)` — $(entry.detail)
"
						);
					} else {
						stream.puts(@"- `$(entry.symbol)`
");
					}
				}
			}

			stream = null;
			GLib.print(
				"gaps %d → %s\n", gap_total, this.missing_out_path
			);
		}
	}
}
