namespace GnomeShellRpc.GiStubGen
{
	/**
	 * Walk an installed typelib via GIRepository and emit Vala stubs.
	 *
	 * {@link Application} is the CLI only; this class owns generation.
	 * Each {@link GI.InfoType} is handled by its own emit method.
	 *
	 * == Example ==
	 *
	 * {{{
	 * var gen = new Generator() { allow = allow };
	 * gen.require("GiRpcSmoke", "1.0");
	 * gen.emit("GiRpcSmoke", "GiRpcSmoke_generated.vala");
	 * }}}
	 */
	public class Generator : GLib.Object
	{
		/**
		 * Optional allowlist of function names or {@code Type.method}.
		 * Empty means all matching infos.
		 */
		public string[] allow { get; set; default = {}; }

		/**
		 * Prepend a typelib search path (same as {@link GI.Repository.prepend_search_path}).
		 *
		 * @param dir directory containing typelibs
		 */
		public void prepend_typelib_dir(string dir)
		{
			GI.Repository.prepend_search_path(dir);
			GLib.debug("typelib prepend %s", dir);
		}

		/**
		 * Load a namespace/version into the default repository.
		 *
		 * @param ns GI namespace (e.g. Meta)
		 * @param version typelib version (e.g. 16)
		 * @throws GLib.Error if the typelib cannot be required
		 */
		public void require(string ns, string version) throws GLib.Error
		{
			GI.Repository.get_default().require(ns, version, 0);
		}

		/**
		 * Write Vala stubs for allowlisted infos in {@code ns}.
		 *
		 * @param ns GI namespace
		 * @param out_path path for the generated {@code .vala} file
		 * @throws GLib.Error if nothing was emitted or the file cannot be written
		 */
		public void emit(string ns, string out_path) throws GLib.Error
		{
			var stream = GLib.FileStream.open(out_path, "w");
			if (stream == null) {
				throw new GLib.IOError.FAILED("cannot write " + out_path);
			}
			stream.puts(@"
/* Generated by gi-stub-gen — do not edit */
namespace $(ns)
{
");

			var emitted = 0;
			var n_infos = GI.Repository.get_default().get_n_infos(ns);
			for (var i = 0; i < n_infos; i++) {
				var info = GI.Repository.get_default().get_info(ns, i);
				switch (info.get_type()) {
					case GI.InfoType.FUNCTION:
						emitted += this.emit_function(stream, ns, (GI.FunctionInfo)info);
						continue;
					case GI.InfoType.OBJECT:
						emitted += this.emit_object(stream, ns, (GI.ObjectInfo)info);
						continue;
					case GI.InfoType.ENUM:
						emitted += this.emit_enum(stream, (GI.EnumInfo)info);
						continue;
					case GI.InfoType.FLAGS:
						emitted += this.emit_flags(stream, (GI.EnumInfo)info);
						continue;
					case GI.InfoType.CONSTANT:
						emitted += this.emit_constant(stream, (GI.ConstantInfo)info);
						continue;
					case GI.InfoType.STRUCT:
						emitted += this.emit_struct(stream, ns, (GI.StructInfo)info);
						continue;
					case GI.InfoType.INTERFACE:
						emitted += this.emit_interface(stream, ns, (GI.InterfaceInfo)info);
						continue;
					case GI.InfoType.CALLBACK:
						emitted += this.emit_callback(stream, ns, (GI.CallbackInfo)info);
						continue;
					default:
						GLib.debug("unhandled %s %s", info.get_type().to_string(), info.get_name());
						continue;
				}
			}
			stream.puts("}\n");
			stream = null;

			if (emitted == 0) {
				GLib.FileUtils.unlink(out_path);
				throw new GLib.IOError.FAILED("emit: no matching stubs");
			}
			GLib.print("emitted %d stub(s) → %s\n", emitted, out_path);
		}

		/**
		 * Emit a namespace function.
		 *
		 * @param stream output Vala file
		 * @param ns GI namespace
		 * @param fi function info
		 * @return number of stubs written (0 or 1)
		 */
		private int emit_function(GLib.FileStream stream, string ns, GI.FunctionInfo fi)
		{
			if (!this.allow_hit(fi.get_name(), "")) {
				return 0;
			}
			return this.emit_callable(stream, ns, "", fi, "ns");
		}

		/**
		 * Emit an object type and recurse into its methods.
		 *
		 * @param stream output Vala file
		 * @param ns GI namespace
		 * @param oi object info
		 * @return number of stubs written (class counts as 1 when emitted)
		 */
		private int emit_object(GLib.FileStream stream, string ns, GI.ObjectInfo oi)
		{
			if (this.allow.length > 0 && !this.allow_hit(oi.get_name(), "")) {
				var any = false;
				for (var m = 0; m < oi.get_n_methods(); m++) {
					if (this.allow_hit(oi.get_method(m).get_name(), oi.get_name())) {
						any = true;
						break;
					}
				}
				if (!any) {
					return 0;
				}
			}

			var parent = "GLib.Object";
			if (oi.get_parent() != null) {
				parent = this.info_name(ns, oi.get_parent());
			}

			stream.puts(@"
	public class $(oi.get_name()) : $(parent)
	{
");
			var methods = 0;
			for (var m = 0; m < oi.get_n_methods(); m++) {
				methods += this.emit_callable(stream, ns, oi.get_name(), oi.get_method(m), "class");
			}
			stream.puts("	}\n");
			return 1 + methods;
		}

		/**
		 * Emit an enum type.
		 *
		 * @param stream output Vala file
		 * @param ei enum info
		 * @return 1 if written
		 */
		private int emit_enum(GLib.FileStream stream, GI.EnumInfo ei)
		{
			return this.emit_enum_values(stream, ei, false);
		}

		/**
		 * Emit a flags type.
		 *
		 * @param stream output Vala file
		 * @param ei flags info (same GI shape as enum)
		 * @return 1 if written
		 */
		private int emit_flags(GLib.FileStream stream, GI.EnumInfo ei)
		{
			return this.emit_enum_values(stream, ei, true);
		}

		private int emit_enum_values(GLib.FileStream stream, GI.EnumInfo ei, bool is_flags)
		{
			if (!this.allow_hit(ei.get_name(), "")) {
				return 0;
			}
			if (is_flags) {
				stream.puts("\n	[Flags]\n");
			} else {
				stream.puts("\n");
			}
			stream.puts(@"	public enum $(ei.get_name())
	{
");
			for (var i = 0; i < ei.get_n_values(); i++) {
				var vi = ei.get_value(i);
				stream.puts(@"		$(vi.get_name()) = $(vi.get_value()),
");
			}
			stream.puts("	}\n");
			return 1;
		}

		/**
		 * Emit a namespace constant.
		 *
		 * @param stream output Vala file
		 * @param ci constant info
		 * @return 1 if written
		 */
		private int emit_constant(GLib.FileStream stream, GI.ConstantInfo ci)
		{
			if (!this.allow_hit(ci.get_name(), "")) {
				return 0;
			}
			GI.Argument value;
			ci.get_value(out value);
			switch (ci.get_type().get_tag()) {
				case GI.TypeTag.BOOLEAN:
					stream.puts(@"
	public const bool $(ci.get_name()) = $(value.v_boolean);
");
					return 1;
				case GI.TypeTag.INT8:
					stream.puts(@"
	public const int8 $(ci.get_name()) = $(value.v_int8);
");
					return 1;
				case GI.TypeTag.UINT8:
					stream.puts(@"
	public const uint8 $(ci.get_name()) = $(value.v_uint8);
");
					return 1;
				case GI.TypeTag.INT16:
					stream.puts(@"
	public const int16 $(ci.get_name()) = $(value.v_int16);
");
					return 1;
				case GI.TypeTag.UINT16:
					stream.puts(@"
	public const uint16 $(ci.get_name()) = $(value.v_uint16);
");
					return 1;
				case GI.TypeTag.INT32:
					stream.puts(@"
	public const int32 $(ci.get_name()) = $(value.v_int32);
");
					return 1;
				case GI.TypeTag.UINT32:
					stream.puts(@"
	public const uint32 $(ci.get_name()) = $(value.v_uint32);
");
					return 1;
				case GI.TypeTag.INT64:
					stream.puts(@"
	public const int64 $(ci.get_name()) = $(value.v_int64);
");
					return 1;
				case GI.TypeTag.UINT64:
					stream.puts(@"
	public const uint64 $(ci.get_name()) = $(value.v_uint64);
");
					return 1;
				case GI.TypeTag.FLOAT:
					stream.puts(@"
	public const float $(ci.get_name()) = $(value.v_float);
");
					return 1;
				case GI.TypeTag.DOUBLE:
					stream.puts(@"
	public const double $(ci.get_name()) = $(value.v_double);
");
					return 1;
				case GI.TypeTag.UTF8:
				case GI.TypeTag.FILENAME:
					stream.puts(@"
	public const string $(ci.get_name()) = \"$(value.v_string)\";
");
					return 1;
				default:
					GLib.debug("unhandled CONSTANT %s tag=%s",
						ci.get_name(), ci.get_type().get_tag().to_string());
					return 0;
			}
		}

		/**
		 * Emit a struct (skips GType class structs).
		 *
		 * @param stream output Vala file
		 * @param ns GI namespace
		 * @param si struct info
		 * @return 1 if written
		 */
		private int emit_struct(GLib.FileStream stream, string ns, GI.StructInfo si)
		{
			if (si.is_gtype_struct()) {
				GLib.debug("skip STRUCT %s (gtype class struct)", si.get_name());
				return 0;
			}
			if (!this.allow_hit(si.get_name(), "")) {
				return 0;
			}
			stream.puts(@"
	public struct $(si.get_name())
	{
");
			for (var f = 0; f < si.get_n_fields(); f++) {
				var field = si.get_field(f);
				var ft = this.type_vala(ns, field.get_type());
				if (ft == "") {
					GLib.debug("unhandled FIELD %s.%s", si.get_name(), field.get_name());
					continue;
				}
				stream.puts(@"		public $(ft) $(field.get_name());
");
			}
			stream.puts("	}\n");
			return 1;
		}

		/**
		 * Emit an interface and its methods.
		 *
		 * @param stream output Vala file
		 * @param ns GI namespace
		 * @param ii interface info
		 * @return number of stubs written
		 */
		private int emit_interface(GLib.FileStream stream, string ns, GI.InterfaceInfo ii)
		{
			if (this.allow.length > 0 && !this.allow_hit(ii.get_name(), "")) {
				var any = false;
				for (var m = 0; m < ii.get_n_methods(); m++) {
					if (this.allow_hit(ii.get_method(m).get_name(), ii.get_name())) {
						any = true;
						break;
					}
				}
				if (!any) {
					return 0;
				}
			}

			stream.puts(@"
	public interface $(ii.get_name()) : GLib.Object
	{
");
			var methods = 0;
			for (var m = 0; m < ii.get_n_methods(); m++) {
				methods += this.emit_callable(stream, ns, ii.get_name(), ii.get_method(m), "iface");
			}
			stream.puts("	}\n");
			return 1 + methods;
		}

		/**
		 * Emit a callback as a Vala delegate.
		 *
		 * @param stream output Vala file
		 * @param ns GI namespace
		 * @param ci callback info
		 * @return 1 if written
		 */
		private int emit_callback(GLib.FileStream stream, string ns, GI.CallbackInfo ci)
		{
			if (!this.allow_hit(ci.get_name(), "")) {
				return 0;
			}
			var ret = this.type_vala(ns, ci.get_return_type());
			if (ret == "") {
				GLib.debug("unhandled CALLBACK %s (return type)", ci.get_name());
				return 0;
			}
			string[] args = {};
			for (var a = 0; a < ci.get_n_args(); a++) {
				var arg = ci.get_arg(a);
				var at = this.type_vala(ns, arg.get_type());
				if (at == "") {
					GLib.debug("unhandled CALLBACK %s arg %s", ci.get_name(), arg.get_name());
					return 0;
				}
				args += this.arg_decl(arg, at);
			}
			stream.puts(@"
	public delegate $(ret) $(ci.get_name())($(string.joinv(", ", args)));
");
			return 1;
		}

		/**
		 * Emit one callable (namespace function or method) with a stub or utf8 RPC body.
		 *
		 * @param stream output Vala file
		 * @param ns GI namespace
		 * @param type_name owning type name, or empty for namespace functions
		 * @param fi function info
		 * @param kind {@code ns}, {@code class}, or {@code iface}
		 * @return 1 if written
		 */
		private int emit_callable(
			GLib.FileStream stream,
			string ns,
			string type_name,
			GI.FunctionInfo fi,
			string kind
		)
		{
			if (type_name != "" && !this.allow_hit(fi.get_name(), type_name)
				&& !this.allow_hit(type_name, "")) {
				return 0;
			}

			var flags = fi.get_flags();
			if ((flags & GI.FunctionInfoFlags.IS_CONSTRUCTOR) != 0) {
				GLib.debug("unhandled constructor %s.%s", type_name, fi.get_name());
				return 0;
			}

			var ret = this.type_vala(ns, fi.get_return_type());
			if (ret == "") {
				GLib.debug("unhandled callable %s.%s (return)", type_name, fi.get_name());
				return 0;
			}

			string[] args = {};
			for (var a = 0; a < fi.get_n_args(); a++) {
				var arg = fi.get_arg(a);
				var at = this.type_vala(ns, arg.get_type());
				if (at == "") {
					GLib.debug("unhandled callable %s.%s arg %s",
						type_name, fi.get_name(), arg.get_name());
					return 0;
				}
				args += this.arg_decl(arg, at);
			}

			var tab = kind == "ns" ? "	" : "		";
			var arglist = string.joinv(", ", args);
			/*
			 * Domain wire names: no RPC- prefix (Daemon / Live-* only).
			 * Nested type → hyphen object prefix (Meta-Window.minimize),
			 * same idea as RPC-Live-Remote.ref.
			 */
			var rpc = type_name == ""
				? @"$(ns).$(fi.get_name())"
				: @"$(ns)-$(type_name).$(fi.get_name())";

			if (kind == "iface") {
				if (ret == "void") {
					stream.puts(@"
$(tab)public abstract void $(fi.get_name())($(arglist));
");
				} else {
					stream.puts(@"
$(tab)public abstract $(ret) $(fi.get_name())($(arglist));
");
				}
				return 1;
			}

			if (ret == "void") {
				stream.puts(@"
$(tab)public void $(fi.get_name())($(arglist))
$(tab){
$(tab)	GLib.error(\"gi-stub: $(rpc) not wired\");
$(tab)}
");
			} else {
				stream.puts(@"
$(tab)public $(ret) $(fi.get_name())($(arglist))
$(tab){
$(tab)	GLib.error(\"gi-stub: $(rpc) not wired\");
$(tab)}
");
			}
			return 1;
		}

		private string arg_decl(GI.ArgInfo arg, string type_name)
		{
			switch (arg.get_direction()) {
				case GI.Direction.OUT:
					return "out " + type_name + " " + arg.get_name();
				case GI.Direction.INOUT:
					return "ref " + type_name + " " + arg.get_name();
				default:
					return type_name + " " + arg.get_name();
			}
		}

		private string info_name(string ns, GI.BaseInfo info)
		{
			var info_ns = info.get_namespace();
			if (info_ns == null || info_ns == "") {
				return info.get_name();
			}
			if (info_ns == "GObject" && info.get_name() == "Object") {
				return "GLib.Object";
			}
			if (info_ns == ns) {
				return info.get_name();
			}
			if (info_ns == "GObject") {
				return "GLib." + info.get_name();
			}
			return info_ns + "." + info.get_name();
		}

		private string type_vala(string ns, GI.TypeInfo ti)
		{
			switch (ti.get_tag()) {
				case GI.TypeTag.VOID:
					return "void";
				case GI.TypeTag.BOOLEAN:
					return "bool";
				case GI.TypeTag.INT8:
					return "int8";
				case GI.TypeTag.UINT8:
					return "uint8";
				case GI.TypeTag.INT16:
					return "int16";
				case GI.TypeTag.UINT16:
					return "uint16";
				case GI.TypeTag.INT32:
					return "int32";
				case GI.TypeTag.UINT32:
					return "uint32";
				case GI.TypeTag.INT64:
					return "int64";
				case GI.TypeTag.UINT64:
					return "uint64";
				case GI.TypeTag.FLOAT:
					return "float";
				case GI.TypeTag.DOUBLE:
					return "double";
				case GI.TypeTag.GTYPE:
					return "GLib.Type";
				case GI.TypeTag.UTF8:
				case GI.TypeTag.FILENAME:
					return "string";
				case GI.TypeTag.UNICHAR:
					return "unichar";
				case GI.TypeTag.ERROR:
					return "GLib.Error";
				case GI.TypeTag.INTERFACE:
					var iface = ti.get_interface();
					if (iface == null) {
						return "";
					}
					return this.info_name(ns, iface);
				default:
					return "";
			}
		}

		private bool allow_hit(string name, string type_name)
		{
			if (this.allow.length == 0) {
				return true;
			}
			foreach (var allow in this.allow) {
				if (allow == name) {
					return true;
				}
				if (type_name != "" && allow == type_name + "." + name) {
					return true;
				}
			}
			return false;
		}
	}
}
