/* pub_layout.c generated by valac 0.56.18, the Vala compiler
 * generated from pub_layout.vala, do not modify */

#include <glib-object.h>
#include <glib.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define T_TYPE_META (t_meta_get_type ())
#define T_META(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), T_TYPE_META, TMeta))
#define T_META_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), T_TYPE_META, TMetaClass))
#define T_IS_META(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), T_TYPE_META))
#define T_IS_META_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), T_TYPE_META))
#define T_META_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), T_TYPE_META, TMetaClass))

typedef struct _TMeta TMeta;
typedef struct _TMetaClass TMetaClass;
typedef struct _TMetaPrivate TMetaPrivate;
enum  {
	T_META_0_PROPERTY,
	T_META_NUM_PROPERTIES
};
static GParamSpec* t_meta_properties[T_META_NUM_PROPERTIES];

#define T_TYPE_META_PUB (t_meta_pub_get_type ())
#define T_META_PUB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), T_TYPE_META_PUB, TMetaPub))
#define T_META_PUB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), T_TYPE_META_PUB, TMetaPubClass))
#define T_IS_META_PUB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), T_TYPE_META_PUB))
#define T_IS_META_PUB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), T_TYPE_META_PUB))
#define T_META_PUB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), T_TYPE_META_PUB, TMetaPubClass))

typedef struct _TMetaPub TMetaPub;
typedef struct _TMetaPubClass TMetaPubClass;
typedef struct _TMetaPubPrivate TMetaPubPrivate;
enum  {
	T_META_PUB_0_PROPERTY,
	T_META_PUB_NUM_PROPERTIES
};
static GParamSpec* t_meta_pub_properties[T_META_PUB_NUM_PROPERTIES];

#define T_TYPE_META_ATTR (t_meta_attr_get_type ())
#define T_META_ATTR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), T_TYPE_META_ATTR, TMetaAttr))
#define T_META_ATTR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), T_TYPE_META_ATTR, TMetaAttrClass))
#define T_IS_META_ATTR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), T_TYPE_META_ATTR))
#define T_IS_META_ATTR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), T_TYPE_META_ATTR))
#define T_META_ATTR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), T_TYPE_META_ATTR, TMetaAttrClass))

typedef struct _TMetaAttr TMetaAttr;
typedef struct _TMetaAttrClass TMetaAttrClass;
typedef struct _TMetaAttrPrivate TMetaAttrPrivate;
enum  {
	T_META_ATTR_0_PROPERTY,
	T_META_ATTR_NUM_PROPERTIES
};
static GParamSpec* t_meta_attr_properties[T_META_ATTR_NUM_PROPERTIES];

struct _TMeta {
	GInitiallyUnowned parent_instance;
	TMetaPrivate * priv;
};

struct _TMetaClass {
	GInitiallyUnownedClass parent_class;
};

struct _TMetaPub {
	GInitiallyUnowned parent_instance;
	TMetaPubPrivate * priv;
	guint32 flags;
	gint accessible_role;
	guint32 private_flags;
};

struct _TMetaPubClass {
	GInitiallyUnownedClass parent_class;
};

struct _TMetaAttr {
	GInitiallyUnowned parent_instance;
	TMetaAttrPrivate * priv;
	void* data;
};

struct _TMetaAttrClass {
	GInitiallyUnownedClass parent_class;
};

static gpointer t_meta_parent_class = NULL;
static gpointer t_meta_pub_parent_class = NULL;
static gpointer t_meta_attr_parent_class = NULL;

VALA_EXTERN GType t_meta_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (TMeta, g_object_unref)
VALA_EXTERN TMeta* t_meta_new (void);
VALA_EXTERN TMeta* t_meta_construct (GType object_type);
static GType t_meta_get_type_once (void);
VALA_EXTERN GType t_meta_pub_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (TMetaPub, g_object_unref)
VALA_EXTERN TMetaPub* t_meta_pub_new (void);
VALA_EXTERN TMetaPub* t_meta_pub_construct (GType object_type);
static void t_meta_pub_finalize (GObject * obj);
static GType t_meta_pub_get_type_once (void);
VALA_EXTERN GType t_meta_attr_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (TMetaAttr, g_object_unref)
VALA_EXTERN TMetaAttr* t_meta_attr_new (void);
VALA_EXTERN TMetaAttr* t_meta_attr_construct (GType object_type);
static void t_meta_attr_finalize (GObject * obj);
static GType t_meta_attr_get_type_once (void);

TMeta*
t_meta_construct (GType object_type)
{
	TMeta * self = NULL;
	self = (TMeta*) g_object_new (object_type, NULL);
	return self;
}

TMeta*
t_meta_new (void)
{
	return t_meta_construct (T_TYPE_META);
}

static void
t_meta_class_init (TMetaClass * klass,
                   gpointer klass_data)
{
	t_meta_parent_class = g_type_class_peek_parent (klass);
}

static void
t_meta_instance_init (TMeta * self,
                      gpointer klass)
{
}

static GType
t_meta_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (TMetaClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) t_meta_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TMeta), 0, (GInstanceInitFunc) t_meta_instance_init, NULL };
	GType t_meta_type_id;
	t_meta_type_id = g_type_register_static (G_TYPE_INITIALLY_UNOWNED, "TMeta", &g_define_type_info, 0);
	return t_meta_type_id;
}

GType
t_meta_get_type (void)
{
	static volatile gsize t_meta_type_id__once = 0;
	if (g_once_init_enter (&t_meta_type_id__once)) {
		GType t_meta_type_id;
		t_meta_type_id = t_meta_get_type_once ();
		g_once_init_leave (&t_meta_type_id__once, t_meta_type_id);
	}
	return t_meta_type_id__once;
}

TMetaPub*
t_meta_pub_construct (GType object_type)
{
	TMetaPub * self = NULL;
	self = (TMetaPub*) g_object_new (object_type, NULL);
	return self;
}

TMetaPub*
t_meta_pub_new (void)
{
	return t_meta_pub_construct (T_TYPE_META_PUB);
}

static void
t_meta_pub_class_init (TMetaPubClass * klass,
                       gpointer klass_data)
{
	t_meta_pub_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = t_meta_pub_finalize;
}

static void
t_meta_pub_instance_init (TMetaPub * self,
                          gpointer klass)
{
}

static void
t_meta_pub_finalize (GObject * obj)
{
	TMetaPub * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, T_TYPE_META_PUB, TMetaPub);
	G_OBJECT_CLASS (t_meta_pub_parent_class)->finalize (obj);
}

static GType
t_meta_pub_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (TMetaPubClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) t_meta_pub_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TMetaPub), 0, (GInstanceInitFunc) t_meta_pub_instance_init, NULL };
	GType t_meta_pub_type_id;
	t_meta_pub_type_id = g_type_register_static (G_TYPE_INITIALLY_UNOWNED, "TMetaPub", &g_define_type_info, 0);
	return t_meta_pub_type_id;
}

GType
t_meta_pub_get_type (void)
{
	static volatile gsize t_meta_pub_type_id__once = 0;
	if (g_once_init_enter (&t_meta_pub_type_id__once)) {
		GType t_meta_pub_type_id;
		t_meta_pub_type_id = t_meta_pub_get_type_once ();
		g_once_init_leave (&t_meta_pub_type_id__once, t_meta_pub_type_id);
	}
	return t_meta_pub_type_id__once;
}

TMetaAttr*
t_meta_attr_construct (GType object_type)
{
	TMetaAttr * self = NULL;
	self = (TMetaAttr*) g_object_new (object_type, NULL);
	return self;
}

TMetaAttr*
t_meta_attr_new (void)
{
	return t_meta_attr_construct (T_TYPE_META_ATTR);
}

static void
t_meta_attr_class_init (TMetaAttrClass * klass,
                        gpointer klass_data)
{
	t_meta_attr_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = t_meta_attr_finalize;
}

static void
t_meta_attr_instance_init (TMetaAttr * self,
                           gpointer klass)
{
}

static void
t_meta_attr_finalize (GObject * obj)
{
	TMetaAttr * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, T_TYPE_META_ATTR, TMetaAttr);
	G_OBJECT_CLASS (t_meta_attr_parent_class)->finalize (obj);
}

static GType
t_meta_attr_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (TMetaAttrClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) t_meta_attr_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TMetaAttr), 0, (GInstanceInitFunc) t_meta_attr_instance_init, NULL };
	GType t_meta_attr_type_id;
	t_meta_attr_type_id = g_type_register_static (G_TYPE_INITIALLY_UNOWNED, "TMetaAttr", &g_define_type_info, 0);
	return t_meta_attr_type_id;
}

GType
t_meta_attr_get_type (void)
{
	static volatile gsize t_meta_attr_type_id__once = 0;
	if (g_once_init_enter (&t_meta_attr_type_id__once)) {
		GType t_meta_attr_type_id;
		t_meta_attr_type_id = t_meta_attr_get_type_once ();
		g_once_init_leave (&t_meta_attr_type_id__once, t_meta_attr_type_id);
	}
	return t_meta_attr_type_id__once;
}

