/* PubLayout.c generated by valac 0.56.18, the Vala compiler
 * generated from PubLayout.vala, do not modify */

#include <glib-object.h>
#include <glib.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define LAYOUT_TYPE_EMPTY_META (layout_empty_meta_get_type ())
#define LAYOUT_EMPTY_META(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LAYOUT_TYPE_EMPTY_META, LayoutEmptyMeta))
#define LAYOUT_EMPTY_META_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LAYOUT_TYPE_EMPTY_META, LayoutEmptyMetaClass))
#define LAYOUT_IS_EMPTY_META(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LAYOUT_TYPE_EMPTY_META))
#define LAYOUT_IS_EMPTY_META_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LAYOUT_TYPE_EMPTY_META))
#define LAYOUT_EMPTY_META_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LAYOUT_TYPE_EMPTY_META, LayoutEmptyMetaClass))

typedef struct _LayoutEmptyMeta LayoutEmptyMeta;
typedef struct _LayoutEmptyMetaClass LayoutEmptyMetaClass;
typedef struct _LayoutEmptyMetaPrivate LayoutEmptyMetaPrivate;
enum  {
	LAYOUT_EMPTY_META_0_PROPERTY,
	LAYOUT_EMPTY_META_NUM_PROPERTIES
};
static GParamSpec* layout_empty_meta_properties[LAYOUT_EMPTY_META_NUM_PROPERTIES];

#define LAYOUT_TYPE_PUBLIC_ONLY (layout_public_only_get_type ())
#define LAYOUT_PUBLIC_ONLY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LAYOUT_TYPE_PUBLIC_ONLY, LayoutPublicOnly))
#define LAYOUT_PUBLIC_ONLY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LAYOUT_TYPE_PUBLIC_ONLY, LayoutPublicOnlyClass))
#define LAYOUT_IS_PUBLIC_ONLY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LAYOUT_TYPE_PUBLIC_ONLY))
#define LAYOUT_IS_PUBLIC_ONLY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LAYOUT_TYPE_PUBLIC_ONLY))
#define LAYOUT_PUBLIC_ONLY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LAYOUT_TYPE_PUBLIC_ONLY, LayoutPublicOnlyClass))

typedef struct _LayoutPublicOnly LayoutPublicOnly;
typedef struct _LayoutPublicOnlyClass LayoutPublicOnlyClass;
typedef struct _LayoutPublicOnlyPrivate LayoutPublicOnlyPrivate;
enum  {
	LAYOUT_PUBLIC_ONLY_0_PROPERTY,
	LAYOUT_PUBLIC_ONLY_NUM_PROPERTIES
};
static GParamSpec* layout_public_only_properties[LAYOUT_PUBLIC_ONLY_NUM_PROPERTIES];

#define LAYOUT_TYPE_PUBLIC_WITH_PRIV_FIELD (layout_public_with_priv_field_get_type ())
#define LAYOUT_PUBLIC_WITH_PRIV_FIELD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LAYOUT_TYPE_PUBLIC_WITH_PRIV_FIELD, LayoutPublicWithPrivField))
#define LAYOUT_PUBLIC_WITH_PRIV_FIELD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LAYOUT_TYPE_PUBLIC_WITH_PRIV_FIELD, LayoutPublicWithPrivFieldClass))
#define LAYOUT_IS_PUBLIC_WITH_PRIV_FIELD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LAYOUT_TYPE_PUBLIC_WITH_PRIV_FIELD))
#define LAYOUT_IS_PUBLIC_WITH_PRIV_FIELD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LAYOUT_TYPE_PUBLIC_WITH_PRIV_FIELD))
#define LAYOUT_PUBLIC_WITH_PRIV_FIELD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LAYOUT_TYPE_PUBLIC_WITH_PRIV_FIELD, LayoutPublicWithPrivFieldClass))

typedef struct _LayoutPublicWithPrivField LayoutPublicWithPrivField;
typedef struct _LayoutPublicWithPrivFieldClass LayoutPublicWithPrivFieldClass;
typedef struct _LayoutPublicWithPrivFieldPrivate LayoutPublicWithPrivFieldPrivate;
enum  {
	LAYOUT_PUBLIC_WITH_PRIV_FIELD_0_PROPERTY,
	LAYOUT_PUBLIC_WITH_PRIV_FIELD_NUM_PROPERTIES
};
static GParamSpec* layout_public_with_priv_field_properties[LAYOUT_PUBLIC_WITH_PRIV_FIELD_NUM_PROPERTIES];

struct _LayoutEmptyMeta {
	GInitiallyUnowned parent_instance;
	LayoutEmptyMetaPrivate * priv;
};

struct _LayoutEmptyMetaClass {
	GInitiallyUnownedClass parent_class;
};

struct _LayoutPublicOnly {
	GInitiallyUnowned parent_instance;
	LayoutPublicOnlyPrivate * priv;
	guint32 flags;
	gint accessible_role;
	guint32 private_flags;
};

struct _LayoutPublicOnlyClass {
	GInitiallyUnownedClass parent_class;
};

struct _LayoutPublicWithPrivField {
	GInitiallyUnowned parent_instance;
	LayoutPublicWithPrivFieldPrivate * priv;
	guint32 flags;
};

struct _LayoutPublicWithPrivFieldClass {
	GInitiallyUnownedClass parent_class;
};

struct _LayoutPublicWithPrivFieldPrivate {
	gint hidden;
};

static gpointer layout_empty_meta_parent_class = NULL;
static gpointer layout_public_only_parent_class = NULL;
static gint LayoutPublicWithPrivField_private_offset;
static gpointer layout_public_with_priv_field_parent_class = NULL;

VALA_EXTERN GType layout_empty_meta_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (LayoutEmptyMeta, g_object_unref)
VALA_EXTERN LayoutEmptyMeta* layout_empty_meta_new (void);
VALA_EXTERN LayoutEmptyMeta* layout_empty_meta_construct (GType object_type);
static GType layout_empty_meta_get_type_once (void);
VALA_EXTERN GType layout_public_only_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (LayoutPublicOnly, g_object_unref)
VALA_EXTERN LayoutPublicOnly* layout_public_only_new (void);
VALA_EXTERN LayoutPublicOnly* layout_public_only_construct (GType object_type);
static void layout_public_only_finalize (GObject * obj);
static GType layout_public_only_get_type_once (void);
VALA_EXTERN GType layout_public_with_priv_field_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (LayoutPublicWithPrivField, g_object_unref)
VALA_EXTERN LayoutPublicWithPrivField* layout_public_with_priv_field_new (void);
VALA_EXTERN LayoutPublicWithPrivField* layout_public_with_priv_field_construct (GType object_type);
static void layout_public_with_priv_field_finalize (GObject * obj);
static GType layout_public_with_priv_field_get_type_once (void);

LayoutEmptyMeta*
layout_empty_meta_construct (GType object_type)
{
	LayoutEmptyMeta * self = NULL;
	self = (LayoutEmptyMeta*) g_object_new (object_type, NULL);
	return self;
}

LayoutEmptyMeta*
layout_empty_meta_new (void)
{
	return layout_empty_meta_construct (LAYOUT_TYPE_EMPTY_META);
}

static void
layout_empty_meta_class_init (LayoutEmptyMetaClass * klass,
                              gpointer klass_data)
{
	layout_empty_meta_parent_class = g_type_class_peek_parent (klass);
}

static void
layout_empty_meta_instance_init (LayoutEmptyMeta * self,
                                 gpointer klass)
{
}

static GType
layout_empty_meta_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (LayoutEmptyMetaClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) layout_empty_meta_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LayoutEmptyMeta), 0, (GInstanceInitFunc) layout_empty_meta_instance_init, NULL };
	GType layout_empty_meta_type_id;
	layout_empty_meta_type_id = g_type_register_static (G_TYPE_INITIALLY_UNOWNED, "LayoutEmptyMeta", &g_define_type_info, 0);
	return layout_empty_meta_type_id;
}

GType
layout_empty_meta_get_type (void)
{
	static volatile gsize layout_empty_meta_type_id__once = 0;
	if (g_once_init_enter (&layout_empty_meta_type_id__once)) {
		GType layout_empty_meta_type_id;
		layout_empty_meta_type_id = layout_empty_meta_get_type_once ();
		g_once_init_leave (&layout_empty_meta_type_id__once, layout_empty_meta_type_id);
	}
	return layout_empty_meta_type_id__once;
}

LayoutPublicOnly*
layout_public_only_construct (GType object_type)
{
	LayoutPublicOnly * self = NULL;
	self = (LayoutPublicOnly*) g_object_new (object_type, NULL);
	return self;
}

LayoutPublicOnly*
layout_public_only_new (void)
{
	return layout_public_only_construct (LAYOUT_TYPE_PUBLIC_ONLY);
}

static void
layout_public_only_class_init (LayoutPublicOnlyClass * klass,
                               gpointer klass_data)
{
	layout_public_only_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = layout_public_only_finalize;
}

static void
layout_public_only_instance_init (LayoutPublicOnly * self,
                                  gpointer klass)
{
}

static void
layout_public_only_finalize (GObject * obj)
{
	LayoutPublicOnly * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, LAYOUT_TYPE_PUBLIC_ONLY, LayoutPublicOnly);
	G_OBJECT_CLASS (layout_public_only_parent_class)->finalize (obj);
}

static GType
layout_public_only_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (LayoutPublicOnlyClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) layout_public_only_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LayoutPublicOnly), 0, (GInstanceInitFunc) layout_public_only_instance_init, NULL };
	GType layout_public_only_type_id;
	layout_public_only_type_id = g_type_register_static (G_TYPE_INITIALLY_UNOWNED, "LayoutPublicOnly", &g_define_type_info, 0);
	return layout_public_only_type_id;
}

GType
layout_public_only_get_type (void)
{
	static volatile gsize layout_public_only_type_id__once = 0;
	if (g_once_init_enter (&layout_public_only_type_id__once)) {
		GType layout_public_only_type_id;
		layout_public_only_type_id = layout_public_only_get_type_once ();
		g_once_init_leave (&layout_public_only_type_id__once, layout_public_only_type_id);
	}
	return layout_public_only_type_id__once;
}

static inline gpointer
layout_public_with_priv_field_get_instance_private (LayoutPublicWithPrivField* self)
{
	return G_STRUCT_MEMBER_P (self, LayoutPublicWithPrivField_private_offset);
}

LayoutPublicWithPrivField*
layout_public_with_priv_field_construct (GType object_type)
{
	LayoutPublicWithPrivField * self = NULL;
	self = (LayoutPublicWithPrivField*) g_object_new (object_type, NULL);
	return self;
}

LayoutPublicWithPrivField*
layout_public_with_priv_field_new (void)
{
	return layout_public_with_priv_field_construct (LAYOUT_TYPE_PUBLIC_WITH_PRIV_FIELD);
}

static void
layout_public_with_priv_field_class_init (LayoutPublicWithPrivFieldClass * klass,
                                          gpointer klass_data)
{
	layout_public_with_priv_field_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &LayoutPublicWithPrivField_private_offset);
	G_OBJECT_CLASS (klass)->finalize = layout_public_with_priv_field_finalize;
}

static void
layout_public_with_priv_field_instance_init (LayoutPublicWithPrivField * self,
                                             gpointer klass)
{
	self->priv = layout_public_with_priv_field_get_instance_private (self);
}

static void
layout_public_with_priv_field_finalize (GObject * obj)
{
	LayoutPublicWithPrivField * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, LAYOUT_TYPE_PUBLIC_WITH_PRIV_FIELD, LayoutPublicWithPrivField);
	G_OBJECT_CLASS (layout_public_with_priv_field_parent_class)->finalize (obj);
}

static GType
layout_public_with_priv_field_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (LayoutPublicWithPrivFieldClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) layout_public_with_priv_field_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LayoutPublicWithPrivField), 0, (GInstanceInitFunc) layout_public_with_priv_field_instance_init, NULL };
	GType layout_public_with_priv_field_type_id;
	layout_public_with_priv_field_type_id = g_type_register_static (G_TYPE_INITIALLY_UNOWNED, "LayoutPublicWithPrivField", &g_define_type_info, 0);
	LayoutPublicWithPrivField_private_offset = g_type_add_instance_private (layout_public_with_priv_field_type_id, sizeof (LayoutPublicWithPrivFieldPrivate));
	return layout_public_with_priv_field_type_id;
}

GType
layout_public_with_priv_field_get_type (void)
{
	static volatile gsize layout_public_with_priv_field_type_id__once = 0;
	if (g_once_init_enter (&layout_public_with_priv_field_type_id__once)) {
		GType layout_public_with_priv_field_type_id;
		layout_public_with_priv_field_type_id = layout_public_with_priv_field_get_type_once ();
		g_once_init_leave (&layout_public_with_priv_field_type_id__once, layout_public_with_priv_field_type_id);
	}
	return layout_public_with_priv_field_type_id__once;
}

