/* t.c generated by valac 0.56.18, the Vala compiler
 * generated from t.vala, do not modify */

#include <stdlib.h>
#include <string.h>
#include <glib.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

static void _vala_main (void);

static void
_vala_main (void)
{
	const gchar* s = NULL;
	void* p = NULL;
	guint u = 0U;
	s = "x";
	p = (void*) s;
	u = (guint) ((guint64) p);
	g_print ("%u\n", u);
}

int
main (int argc,
      char ** argv)
{
	_vala_main ();
	return 0;
}

