/* t3.c generated by valac 0.56.18, the Vala compiler
 * generated from t3.vala, do not modify */

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <stdio.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

#define _g_free0(var) (var = (g_free (var), NULL))

static void _vala_main (void);

static const gchar*
string_to_string (const gchar* self)
{
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}

static void
_vala_main (void)
{
	gchar* fn = NULL;
	gchar* _tmp0_;
	gchar* arg = NULL;
	gchar* _tmp1_;
	FILE* _tmp2_;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	_tmp0_ = g_strdup ("ping");
	fn = _tmp0_;
	_tmp1_ = g_strdup ("msg");
	arg = _tmp1_;
	_tmp2_ = stdout;
	_tmp3_ = string_to_string (fn);
	_tmp4_ = string_to_string (arg);
	_tmp5_ = g_strconcat ("\n	public string ", _tmp3_, "(string ", _tmp4_, ")\n", NULL);
	_tmp6_ = _tmp5_;
	fputs (_tmp6_, _tmp2_);
	_g_free0 (_tmp6_);
	_g_free0 (arg);
	_g_free0 (fn);
}

int
main (int argc,
      char ** argv)
{
	_vala_main ();
	return 0;
}

