/* t4.c generated by valac 0.56.18, the Vala compiler
 * generated from t4.vala, do not modify */

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <stdio.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

#define _g_free0(var) (var = (g_free (var), NULL))

static void _vala_main (void);

static const gchar*
string_to_string (const gchar* self)
{
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}

static void
_vala_main (void)
{
	gchar* fn_name = NULL;
	gchar* _tmp0_;
	gchar* arg_name = NULL;
	gchar* _tmp1_;
	gchar* method_lit = NULL;
	gchar* _tmp2_;
	FILE* _tmp3_;
	const gchar* _tmp4_;
	const gchar* _tmp5_;
	const gchar* _tmp6_;
	const gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	_tmp0_ = g_strdup ("ping");
	fn_name = _tmp0_;
	_tmp1_ = g_strdup ("msg");
	arg_name = _tmp1_;
	_tmp2_ = g_strdup ("\"RPC-x.ping\"");
	method_lit = _tmp2_;
	_tmp3_ = stdout;
	_tmp4_ = string_to_string (fn_name);
	_tmp5_ = string_to_string (arg_name);
	_tmp6_ = string_to_string (method_lit);
	_tmp7_ = string_to_string (arg_name);
	_tmp8_ = g_strconcat ("\n	public string ", _tmp4_, "(string ", _tmp5_, ")\n	{\n		return Runtime.call_utf8(", _tmp6_, ", ", _tmp7_, ");\n	}\n", NULL);
	_tmp9_ = _tmp8_;
	fputs (_tmp9_, _tmp3_);
	_g_free0 (_tmp9_);
	_g_free0 (method_lit);
	_g_free0 (arg_name);
	_g_free0 (fn_name);
}

int
main (int argc,
      char ** argv)
{
	_vala_main ();
	return 0;
}

