/* t6.c generated by valac 0.56.18, the Vala compiler
 * generated from t6.vala, do not modify */

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <stdio.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

#define _g_free0(var) (var = (g_free (var), NULL))

static void _vala_main (void);

static const gchar*
string_to_string (const gchar* self)
{
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}

static void
_vala_main (void)
{
	gchar* ns = NULL;
	gchar* _tmp0_;
	FILE* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	_tmp0_ = g_strdup ("GiRpcSmoke");
	ns = _tmp0_;
	_tmp1_ = stdout;
	_tmp2_ = string_to_string (ns);
	_tmp3_ = g_strconcat ("/* Generated by gi-stub-gen — do not edit */\nnamespace ", _tmp2_, "\n{\n", NULL);
	_tmp4_ = _tmp3_;
	fputs (_tmp4_, _tmp1_);
	_g_free0 (_tmp4_);
	_g_free0 (ns);
}

int
main (int argc,
      char ** argv)
{
	_vala_main ();
	return 0;
}

