/* t7.c generated by valac 0.56.18, the Vala compiler
 * generated from t7.vala, do not modify */

#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gobject/gvaluecollector.h>
#include <stdio.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define TYPE_FUNC_INFO (func_info_get_type ())
#define FUNC_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_FUNC_INFO, FuncInfo))
#define FUNC_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_FUNC_INFO, FuncInfoClass))
#define IS_FUNC_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_FUNC_INFO))
#define IS_FUNC_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_FUNC_INFO))
#define FUNC_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_FUNC_INFO, FuncInfoClass))

typedef struct _FuncInfo FuncInfo;
typedef struct _FuncInfoClass FuncInfoClass;
typedef struct _FuncInfoPrivate FuncInfoPrivate;
typedef struct _ParamSpecFuncInfo ParamSpecFuncInfo;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _func_info_unref0(var) ((var == NULL) ? NULL : (var = (func_info_unref (var), NULL)))

struct _FuncInfo {
	GTypeInstance parent_instance;
	volatile int ref_count;
	FuncInfoPrivate * priv;
};

struct _FuncInfoClass {
	GTypeClass parent_class;
	void (*finalize) (FuncInfo *self);
};

struct _ParamSpecFuncInfo {
	GParamSpec parent_instance;
};

static gpointer func_info_parent_class = NULL;

VALA_EXTERN gpointer func_info_ref (gpointer instance);
VALA_EXTERN void func_info_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_func_info (const gchar* name,
                                  const gchar* nick,
                                  const gchar* blurb,
                                  GType object_type,
                                  GParamFlags flags);
VALA_EXTERN void value_set_func_info (GValue* value,
                          gpointer v_object);
VALA_EXTERN void value_take_func_info (GValue* value,
                           gpointer v_object);
VALA_EXTERN gpointer value_get_func_info (const GValue* value);
VALA_EXTERN GType func_info_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (FuncInfo, func_info_unref)
VALA_EXTERN gchar* func_info_get_name (FuncInfo* self);
VALA_EXTERN gchar* func_info_get_arg_name (FuncInfo* self);
VALA_EXTERN FuncInfo* func_info_new (void);
VALA_EXTERN FuncInfo* func_info_construct (GType object_type);
static void func_info_finalize (FuncInfo * obj);
static GType func_info_get_type_once (void);
static void _vala_main (void);

gchar*
func_info_get_name (FuncInfo* self)
{
	gchar* _tmp0_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup ("ping");
	result = _tmp0_;
	return result;
}

gchar*
func_info_get_arg_name (FuncInfo* self)
{
	gchar* _tmp0_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup ("msg");
	result = _tmp0_;
	return result;
}

FuncInfo*
func_info_construct (GType object_type)
{
	FuncInfo* self = NULL;
	self = (FuncInfo*) g_type_create_instance (object_type);
	return self;
}

FuncInfo*
func_info_new (void)
{
	return func_info_construct (TYPE_FUNC_INFO);
}

static void
value_func_info_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
value_func_info_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		func_info_unref (value->data[0].v_pointer);
	}
}

static void
value_func_info_copy_value (const GValue* src_value,
                            GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = func_info_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
value_func_info_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
value_func_info_collect_value (GValue* value,
                               guint n_collect_values,
                               GTypeCValue* collect_values,
                               guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		FuncInfo * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = func_info_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
value_func_info_lcopy_value (const GValue* value,
                             guint n_collect_values,
                             GTypeCValue* collect_values,
                             guint collect_flags)
{
	FuncInfo ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = func_info_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
param_spec_func_info (const gchar* name,
                      const gchar* nick,
                      const gchar* blurb,
                      GType object_type,
                      GParamFlags flags)
{
	ParamSpecFuncInfo* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_FUNC_INFO), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
value_get_func_info (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_FUNC_INFO), NULL);
	return value->data[0].v_pointer;
}

void
value_set_func_info (GValue* value,
                     gpointer v_object)
{
	FuncInfo * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_FUNC_INFO));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_FUNC_INFO));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		func_info_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		func_info_unref (old);
	}
}

void
value_take_func_info (GValue* value,
                      gpointer v_object)
{
	FuncInfo * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_FUNC_INFO));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_FUNC_INFO));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		func_info_unref (old);
	}
}

static void
func_info_class_init (FuncInfoClass * klass,
                      gpointer klass_data)
{
	func_info_parent_class = g_type_class_peek_parent (klass);
	((FuncInfoClass *) klass)->finalize = func_info_finalize;
}

static void
func_info_instance_init (FuncInfo * self,
                         gpointer klass)
{
	self->ref_count = 1;
}

static void
func_info_finalize (FuncInfo * obj)
{
	FuncInfo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_FUNC_INFO, FuncInfo);
	g_signal_handlers_destroy (self);
}

static GType
func_info_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { value_func_info_init, value_func_info_free_value, value_func_info_copy_value, value_func_info_peek_pointer, "p", value_func_info_collect_value, "p", value_func_info_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (FuncInfoClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) func_info_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (FuncInfo), 0, (GInstanceInitFunc) func_info_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType func_info_type_id;
	func_info_type_id = g_type_register_fundamental (g_type_fundamental_next (), "FuncInfo", &g_define_type_info, &g_define_type_fundamental_info, 0);
	return func_info_type_id;
}

GType
func_info_get_type (void)
{
	static volatile gsize func_info_type_id__once = 0;
	if (g_once_init_enter (&func_info_type_id__once)) {
		GType func_info_type_id;
		func_info_type_id = func_info_get_type_once ();
		g_once_init_leave (&func_info_type_id__once, func_info_type_id);
	}
	return func_info_type_id__once;
}

gpointer
func_info_ref (gpointer instance)
{
	FuncInfo * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
func_info_unref (gpointer instance)
{
	FuncInfo * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		FUNC_INFO_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

static const gchar*
string_to_string (const gchar* self)
{
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}

static void
_vala_main (void)
{
	FuncInfo* fi = NULL;
	FuncInfo* _tmp0_;
	gchar* ns = NULL;
	gchar* _tmp1_;
	FILE* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	const gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	const gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	gchar* _tmp17_;
	gchar* _tmp18_;
	const gchar* _tmp19_;
	gchar* _tmp20_;
	gchar* _tmp21_;
	const gchar* _tmp22_;
	gchar* _tmp23_;
	gchar* _tmp24_;
	_tmp0_ = func_info_new ();
	fi = _tmp0_;
	_tmp1_ = g_strdup ("GiRpcSmoke");
	ns = _tmp1_;
	_tmp2_ = stdout;
	_tmp3_ = func_info_get_name (fi);
	_tmp4_ = _tmp3_;
	_tmp5_ = string_to_string (_tmp4_);
	_tmp6_ = func_info_get_arg_name (fi);
	_tmp7_ = _tmp6_;
	_tmp8_ = string_to_string (_tmp7_);
	_tmp9_ = g_strconcat ("\"RPC-", ns, NULL);
	_tmp10_ = _tmp9_;
	_tmp11_ = g_strconcat (_tmp10_, ".", NULL);
	_tmp12_ = _tmp11_;
	_tmp13_ = func_info_get_name (fi);
	_tmp14_ = _tmp13_;
	_tmp15_ = g_strconcat (_tmp12_, _tmp14_, NULL);
	_tmp16_ = _tmp15_;
	_tmp17_ = g_strconcat (_tmp16_, "\"", NULL);
	_tmp18_ = _tmp17_;
	_tmp19_ = string_to_string (_tmp18_);
	_tmp20_ = func_info_get_arg_name (fi);
	_tmp21_ = _tmp20_;
	_tmp22_ = string_to_string (_tmp21_);
	_tmp23_ = g_strconcat ("\n	public string ", _tmp5_, "(string ", _tmp8_, ")\n	{\n		return Runtime.call_utf8(", _tmp19_, ", ", _tmp22_, ");\n	}\n", NULL);
	_tmp24_ = _tmp23_;
	fputs (_tmp24_, _tmp2_);
	_g_free0 (_tmp24_);
	_g_free0 (_tmp21_);
	_g_free0 (_tmp18_);
	_g_free0 (_tmp16_);
	_g_free0 (_tmp14_);
	_g_free0 (_tmp12_);
	_g_free0 (_tmp10_);
	_g_free0 (_tmp7_);
	_g_free0 (_tmp4_);
	_g_free0 (ns);
	_func_info_unref0 (fi);
}

int
main (int argc,
      char ** argv)
{
	_vala_main ();
	return 0;
}

