/* tactor.c generated by valac 0.56.18, the Vala compiler
 * generated from tactor.vala, do not modify */

#include <glib-object.h>
#include <glib.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define CLUTTER_TYPE_ACTOR (actor_get_type ())
#define ACTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CLUTTER_TYPE_ACTOR, Actor))
#define ACTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CLUTTER_TYPE_ACTOR, ActorClass))
#define IS_ACTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CLUTTER_TYPE_ACTOR))
#define IS_ACTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CLUTTER_TYPE_ACTOR))
#define ACTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CLUTTER_TYPE_ACTOR, ActorClass))

typedef struct _Actor Actor;
typedef struct _ActorClass ActorClass;
typedef struct _ActorPrivate ActorPrivate;
enum  {
	ACTOR_0_PROPERTY,
	ACTOR_NUM_PROPERTIES
};
static GParamSpec* actor_properties[ACTOR_NUM_PROPERTIES];

struct _Actor {
	GInitiallyUnowned parent_instance;
	ActorPrivate * priv;
};

struct _ActorClass {
	GInitiallyUnownedClass parent_class;
};

static gpointer actor_parent_class = NULL;

VALA_EXTERN GType actor_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Actor, g_object_unref)
VALA_EXTERN Actor* actor_new (void);
VALA_EXTERN Actor* actor_construct (GType object_type);
VALA_EXTERN void actor_show (Actor* self);
static GType actor_get_type_once (void);
static void _vala_main (void);

Actor*
actor_new (void)
{
	return actor_construct (CLUTTER_TYPE_ACTOR);
}

void
actor_show (Actor* self)
{
	FILE* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = stdout;
	fprintf (_tmp0_, "show\n");
}

static void
actor_class_init (ActorClass * klass,
                  gpointer klass_data)
{
	actor_parent_class = g_type_class_peek_parent (klass);
}

static void
actor_instance_init (Actor * self,
                     gpointer klass)
{
}

static GType
actor_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ActorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) actor_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Actor), 0, (GInstanceInitFunc) actor_instance_init, NULL };
	GType actor_type_id;
	actor_type_id = g_type_register_static (G_TYPE_INITIALLY_UNOWNED, "Actor", &g_define_type_info, 0);
	return actor_type_id;
}

GType
actor_get_type (void)
{
	static volatile gsize actor_type_id__once = 0;
	if (g_once_init_enter (&actor_type_id__once)) {
		GType actor_type_id;
		actor_type_id = actor_get_type_once ();
		g_once_init_leave (&actor_type_id__once, actor_type_id);
	}
	return actor_type_id__once;
}

static void
_vala_main (void)
{
	GType t = 0UL;
	FILE* _tmp0_;
	const gchar* _tmp1_;
	t = CLUTTER_TYPE_ACTOR;
	_tmp0_ = stdout;
	_tmp1_ = g_type_name (t);
	fprintf (_tmp0_, "%s\n", _tmp1_);
}

int
main (int argc,
      char ** argv)
{
	_vala_main ();
	return 0;
}

