#!/usr/bin/env bash
# Weston in an X11 window for **looking** at the nested shell.
# Nest stays up until you close the Weston window.
#
#   ./scripts/weston-gsr-session.sh
#
# Agent prove (auto-closes Weston): ./scripts/weston-gsr-prove.sh
# Smoke, Weston stays up: GI_META_SMOKE=key-smoke ./scripts/weston-gsr-session.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SOCK="${GSR_WESTON_SOCKET:-wayland-gsr}"
RT="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
WIDTH="${GSR_WESTON_WIDTH:-1280}"
HEIGHT="${GSR_WESTON_HEIGHT:-800}"
INI_DIR="${XDG_RUNTIME_DIR:-/tmp}/gsr-weston-$$"
INI="$INI_DIR/weston-gsr.ini"
AUTO="$ROOT/scripts/weston-gsr-autolaunch.sh"
# session = hold until window closed; prove = short timeout (set by weston-gsr-prove.sh)
MODE="${GSR_WESTON_MODE:-session}"
# Weston autolaunch often drops parent exports — prove/hold source this file.
GSR_ENV_FILE="${RT}/gsr-weston-autolaunch.env"

chmod 700 "$RT" 2>/dev/null || true
export XDG_RUNTIME_DIR="$RT"
export GSR_WESTON_MODE="$MODE"

# Leftover nest / dbus-run-session daemons from previous runs.
GSR_CLEAR_WESTON=1 "$ROOT/scripts/clear-nested-dbus.sh"
sleep 0.2

if ! command -v weston >/dev/null; then
	echo "weston-gsr-session: install weston: sudo apt install weston" >&2
	exit 2
fi
if [[ ! -x "$AUTO" ]]; then
	echo "weston-gsr-session: missing $AUTO" >&2
	exit 2
fi

mkdir -p "$INI_DIR"
sed "s|@AUTOLAUNCH@|$AUTO|g" "$ROOT/scripts/weston-gsr.ini.in" >"$INI"

{
	echo "# generated by weston-gsr-session.sh — do not edit"
	echo "GSR_WESTON_MODE=${MODE}"
	[[ "${GSR_WESTON_AUTO_CLOSE:-0}" == "1" ]] && echo "GSR_WESTON_AUTO_CLOSE=1"
	[[ -n "${GSR_NESTED_TIMEOUT:-}" ]] && printf 'GSR_NESTED_TIMEOUT=%q\n' "$GSR_NESTED_TIMEOUT"
	[[ -n "${GSR_NESTED_SETTLE:-}" ]] && printf 'GSR_NESTED_SETTLE=%q\n' "$GSR_NESTED_SETTLE"
	[[ -n "${GSR_NESTED_STAYUP:-}" ]] && printf 'GSR_NESTED_STAYUP=%q\n' "$GSR_NESTED_STAYUP"
	[[ -n "${GSR_NESTED_NO_A4:-}" ]] && printf 'GSR_NESTED_NO_A4=%q\n' "$GSR_NESTED_NO_A4"
	[[ -n "${GI_META_SMOKE:-}" ]] && printf 'GI_META_SMOKE=%q\n' "$GI_META_SMOKE"
	[[ -n "${GI_META_SMOKE_CMD:-}" ]] && printf 'GI_META_SMOKE_CMD=%q\n' "$GI_META_SMOKE_CMD"
	[[ -n "${GI_META_SMOKE_WAIT_MS:-}" ]] && printf 'GI_META_SMOKE_WAIT_MS=%q\n' "$GI_META_SMOKE_WAIT_MS"
	[[ -n "${GI_WAYLAND_LAUNCH_UNSET_DISPLAY:-}" ]] && printf 'GI_WAYLAND_LAUNCH_UNSET_DISPLAY=%q\n' "$GI_WAYLAND_LAUNCH_UNSET_DISPLAY"
	[[ -n "${GI_WAYLAND_LAUNCH_GDK_WAYLAND:-}" ]] && printf 'GI_WAYLAND_LAUNCH_GDK_WAYLAND=%q\n' "$GI_WAYLAND_LAUNCH_GDK_WAYLAND"
	[[ -n "${GI_META_GDB:-}" ]] && printf 'GI_META_GDB=%q\n' "$GI_META_GDB"
	[[ -n "${GI_META_GDB_BIN:-}" ]] && printf 'GI_META_GDB_BIN=%q\n' "$GI_META_GDB_BIN"
	[[ -n "${GI_META_GDB_EX:-}" ]] && printf 'GI_META_GDB_EX=%q\n' "$GI_META_GDB_EX"
	[[ -n "${GI_RPC_JS_OVERRIDE_DIR:-}" ]] && printf 'GI_RPC_JS_OVERRIDE_DIR=%q\n' "$GI_RPC_JS_OVERRIDE_DIR"
	[[ -n "${GI_RPC_GJS_EMBED_DIR:-}" ]] && printf 'GI_RPC_GJS_EMBED_DIR=%q\n' "$GI_RPC_GJS_EMBED_DIR"
	[[ -n "${GI_RPC_LAUNCH_PROBE:-}" ]] && printf 'GI_RPC_LAUNCH_PROBE=%q\n' "$GI_RPC_LAUNCH_PROBE"
	[[ -n "${GI_RPC_REGISTER_CLASS_TRACE:-}" ]] && printf 'GI_RPC_REGISTER_CLASS_TRACE=%q\n' "$GI_RPC_REGISTER_CLASS_TRACE"
	[[ -n "${GI_RPC_APP_SEARCH_OBSERVE:-}" ]] && printf 'GI_RPC_APP_SEARCH_OBSERVE=%q\n' "$GI_RPC_APP_SEARCH_OBSERVE"
	[[ -n "${GSR_MUTTER_RPC:-}" ]] && printf 'GSR_MUTTER_RPC=%q\n' "$GSR_MUTTER_RPC"
} >"$GSR_ENV_FILE"

echo "weston-gsr-session: mode=$MODE socket=$SOCK ${WIDTH}x${HEIGHT}${GI_META_SMOKE:+ smoke=$GI_META_SMOKE}"
if [[ "$MODE" == "prove" ]]; then
	echo "weston-gsr-session: autolaunch → nested prove (short timeout)"
else
	echo "weston-gsr-session: autolaunch → nested shell (close Weston window to stop)"
fi

exec weston \
	--backend=x11-backend.so \
	--width="$WIDTH" \
	--height="$HEIGHT" \
	--socket="$SOCK" \
	--config="$INI"
